/**
 * Curated list of verified, high-performance GGUF models from Hugging Face
 * Contains direct CDN/resolve URLs, quantizations, and size benchmarks
 */
export const CURATED_HF_MODELS = [
  {
    id: 'smollm2-135m-instruct',
    name: 'SmolLM2 135M Instruct',
    provider: 'Hugging Face',
    creator: 'HuggingFaceTB',
    format: 'GGUF',
    quantization: 'Q4_K_M',
    fileSizeGB: 0.11,
    fileSizeBytes: 115000000,
    contextLength: 2048,
    category: 'Lightweight',
    capabilities: { coding: 40, reasoning: 45, chat: 70 },
    description: 'Ultra-lightweight 135M model. Instant loading, negligible memory usage, perfect for fast local tests on any PC.',
    filename: 'smollm2-135m-instruct-q4_k_m.gguf',
    downloadUrl: 'https://huggingface.co/HuggingFaceTB/SmolLM2-135M-Instruct-GGUF/resolve/main/smollm2-135m-instruct-q4_k_m.gguf',
  },
  {
    id: 'smollm2-360m-instruct',
    name: 'SmolLM2 360M Instruct',
    provider: 'Hugging Face',
    creator: 'HuggingFaceTB',
    format: 'GGUF',
    quantization: 'Q4_K_M',
    fileSizeGB: 0.23,
    fileSizeBytes: 240000000,
    contextLength: 4096,
    category: 'Lightweight',
    capabilities: { coding: 55, reasoning: 58, chat: 78 },
    description: 'Crisp, fast responses with low memory footprint (~400 MB RAM). Runs on any laptop or ancient CPU.',
    filename: 'smollm2-360m-instruct-q4_k_m.gguf',
    downloadUrl: 'https://huggingface.co/HuggingFaceTB/SmolLM2-360M-Instruct-GGUF/resolve/main/smollm2-360m-instruct-q4_k_m.gguf',
  },
  {
    id: 'qwen2.5-0.5b-instruct',
    name: 'Qwen 2.5 0.5B Instruct',
    provider: 'Hugging Face',
    creator: 'Qwen',
    format: 'GGUF',
    quantization: 'Q4_K_M',
    fileSizeGB: 0.39,
    fileSizeBytes: 420000000,
    contextLength: 4096,
    category: 'Lightweight',
    capabilities: { coding: 65, reasoning: 68, chat: 82 },
    description: 'Remarkable speed and quality for a sub-billion parameter model. Excellent multilingual and structured outputs.',
    filename: 'qwen2.5-0.5b-instruct-q4_k_m.gguf',
    downloadUrl: 'https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q4_k_m.gguf',
  },
  {
    id: 'llama-3.2-1b-instruct',
    name: 'Llama 3.2 1B Instruct',
    provider: 'Hugging Face',
    creator: 'Meta / bartowski',
    format: 'GGUF',
    quantization: 'Q4_K_M',
    fileSizeGB: 0.88,
    fileSizeBytes: 940000000,
    contextLength: 8192,
    category: 'Balanced',
    capabilities: { coding: 70, reasoning: 72, chat: 88 },
    description: 'State-of-the-art 1B model from Meta with 8K context. Exceptional for mobile and USB usage on standard PCs.',
    filename: 'llama-3.2-1b-instruct-q4_k_m.gguf',
    downloadUrl: 'https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_M.gguf',
  },
  {
    id: 'deepseek-r1-distill-qwen-1.5b',
    name: 'DeepSeek R1 Distill 1.5B',
    provider: 'Hugging Face',
    creator: 'DeepSeek / bartowski',
    format: 'GGUF',
    quantization: 'Q4_K_M',
    fileSizeGB: 1.12,
    fileSizeBytes: 1200000000,
    contextLength: 8192,
    category: 'Reasoning',
    capabilities: { coding: 78, reasoning: 90, chat: 80 },
    description: 'DeepSeek R1 reasoning architecture distilled into 1.5B weights. Shows full chain-of-thought before answering.',
    filename: 'deepseek-r1-distill-qwen-1.5b-q4_k_m.gguf',
    downloadUrl: 'https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-1.5B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M.gguf',
  },
  {
    id: 'qwen2.5-coder-1.5b-instruct',
    name: 'Qwen 2.5 Coder 1.5B Instruct',
    provider: 'Hugging Face',
    creator: 'Qwen / bartowski',
    format: 'GGUF',
    quantization: 'Q4_K_M',
    fileSizeGB: 1.15,
    fileSizeBytes: 1230000000,
    contextLength: 8192,
    category: 'Coding',
    capabilities: { coding: 92, reasoning: 78, chat: 75 },
    description: 'Dedicated code generation and debugging model. Powers the Nexyris Code Assistant and Terminal AI.',
    filename: 'qwen2.5-coder-1.5b-instruct-q4_k_m.gguf',
    downloadUrl: 'https://huggingface.co/bartowski/Qwen2.5-Coder-1.5B-Instruct-GGUF/resolve/main/Qwen2.5-Coder-1.5B-Instruct-Q4_K_M.gguf',
  },
  {
    id: 'llama-3.2-3b-instruct',
    name: 'Llama 3.2 3B Instruct',
    provider: 'Hugging Face',
    creator: 'Meta / bartowski',
    format: 'GGUF',
    quantization: 'Q4_K_M',
    fileSizeGB: 2.02,
    fileSizeBytes: 2170000000,
    contextLength: 8192,
    category: 'Balanced',
    capabilities: { coding: 80, reasoning: 82, chat: 92 },
    description: 'Meta 3B model offering near-7B level conversational intelligence while remaining fast on moderate hardware.',
    filename: 'llama-3.2-3b-instruct-q4_k_m.gguf',
    downloadUrl: 'https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf',
  },
  {
    id: 'phi-3.5-mini-instruct',
    name: 'Phi 3.5 Mini Instruct',
    provider: 'Hugging Face',
    creator: 'Microsoft / bartowski',
    format: 'GGUF',
    quantization: 'Q4_K_M',
    fileSizeGB: 2.21,
    fileSizeBytes: 2370000000,
    contextLength: 8192,
    category: 'Reasoning',
    capabilities: { coding: 84, reasoning: 88, chat: 85 },
    description: 'Microsoft 3.8B model trained on synthetic textbooks. Exceptional logic, math, and structured data handling.',
    filename: 'phi-3.5-mini-instruct-q4_k_m.gguf',
    downloadUrl: 'https://huggingface.co/bartowski/Phi-3.5-mini-instruct-GGUF/resolve/main/Phi-3.5-mini-instruct-Q4_K_M.gguf',
  },
  {
    id: 'mistral-7b-instruct-v0.3',
    name: 'Mistral 7B Instruct v0.3',
    provider: 'Hugging Face',
    creator: 'Mistral AI / bartowski',
    format: 'GGUF',
    quantization: 'Q4_K_M',
    fileSizeGB: 4.37,
    fileSizeBytes: 4690000000,
    contextLength: 8192,
    category: 'General',
    capabilities: { coding: 85, reasoning: 86, chat: 94 },
    description: 'The industry-standard 7B benchmark. Outstanding versatility for general conversation, writing, and analysis.',
    filename: 'mistral-7b-instruct-v0.3-q4_k_m.gguf',
    downloadUrl: 'https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3-Q4_K_M.gguf',
  },
  {
    id: 'deepseek-r1-distill-qwen-7b',
    name: 'DeepSeek R1 Distill 7B',
    provider: 'Hugging Face',
    creator: 'DeepSeek / bartowski',
    format: 'GGUF',
    quantization: 'Q4_K_M',
    fileSizeGB: 4.68,
    fileSizeBytes: 5020000000,
    contextLength: 8192,
    category: 'Reasoning',
    capabilities: { coding: 90, reasoning: 96, chat: 88 },
    description: 'DeepSeek R1 reasoning on Qwen 2.5 7B. Highest reasoning score in the 7B class with detailed step-by-step thinking.',
    filename: 'deepseek-r1-distill-qwen-7b-q4_k_m.gguf',
    downloadUrl: 'https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-7B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf',
  }
];

/**
 * Searches Hugging Face for GGUF models
 */
export async function searchHuggingFace(query = '') {
  try {
    const url = `https://huggingface.co/api/models?search=${encodeURIComponent(query + ' gguf')}&filter=gguf&sort=downloads&direction=-1&limit=15`;
    const res = await fetch(url, { headers: { 'User-Agent': 'Nexyris-Local/1.0' } });
    if (!res.ok) throw new Error(`HF API error ${res.status}`);
    const data = await res.json();
    return data.map(item => ({
      id: item.id.replace('/', '--'),
      name: item.id.split('/').pop(),
      creator: item.id.split('/')[0] || 'Community',
      downloads: item.downloads || 0,
      likes: item.likes || 0,
      tags: item.tags || [],
      hfRepoUrl: `https://huggingface.co/${item.id}`,
    }));
  } catch (err) {
    console.warn('HF search failed, returning filtered curated models:', err.message);
    return CURATED_HF_MODELS.filter(m => 
      !query || m.name.toLowerCase().includes(query.toLowerCase()) || m.category.toLowerCase().includes(query.toLowerCase())
    );
  }
}
